language: csharp
solution: Visual-Novel-Engine.sln
install:
  - nuget restore Visual-Novel-Engine.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Visual-Novel-Engine.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./VNNLangaugeTests/bin/Release/VNNLangaugeTests.dll
