export const GameConfig = {
  UI: {
    textBox: {
      width: 700,
      height: 150,
      xOffset: 180,
      backgroundColor: 0x000000,
      backgroundAlpha: 0.85,
      borderWidth: 2,
      borderColor: 0xffffff,
      borderRadius: 10,
    },
    fonts: {
      family: 'Arial, sans-serif',
      characterNameSize: 24,
      dialogueSize: 20,
      choiceButtonSize: 18,
      titleSize: 48,
      buttonSize: 28,
      buttonTextSize: 28,
    },
    colors: {
      characterName: 0xffd700,
      dialogue: 0xffffff,
      buttonBg: 0xffd700,
      buttonText: 0x000000,
      buttonHoverBg: 0xffffff,
      buttonHoverBorder: 0xffd700,
      choiceBg: 0x1c202c,
      choiceBorder: 0xffffff,
      choiceBorderAlpha: 0.2,
      choiceBgHover: 0xffd700,
      choiceTextHover: 0x000000,
      errorBg: 0xffffff,
      errorText: 0xcc0000,
      overlay: 0xff0000,
    },
    dialogue: {
      wordWrapWidth: 660,
      lineHeight: 30,
      nameOffsetX: 20,
      nameOffsetY: 15,
      textOffsetX: 20,
      textOffsetY: 50,
    },
    choiceBackdrop: {
      enabled: true,
      backgroundColor: 0x000000,
      backgroundAlpha: 0.5,
    },
    choicePanel: {
      enabled: true,
      minWidth: 580,
      paddingX: 40,
      paddingTop: 28,
      paddingBottom: 28,
      titleToDividerGap: 16,
      dividerToButtonGap: 20,
      backgroundColor: 0x0c0f17,
      backgroundAlpha: 0.82,
      borderWidth: 1.5,
      borderColor: 0xffffff,
      borderAlpha: 0.2,
      borderRadius: 14,
      shadowColor: 0x000000,
      shadowAlpha: 0.35,
      showDivider: true,
      dividerColor: 0xffffff,
      dividerAlpha: 0.12,
    },
    choiceButton: {
      width: 500,
      height: 50,
      spacing: 65,
      borderRadius: 8,
      alpha: 0.85,
    },
  },
  Character: {
    targetHeightRatio: 0.8,
    leftPositionRatio: 0.1,
    rightPositionRatio: 0.9,
    anchorY: 1,
  },
  Animation: {
    defaultDuration: 500,
    transitionDuration: 300,
    choiceFadeDuration: 200,
  },
  Title: {
    fontFamily: 'Georgia, serif',
    color: 0xffd700,
  },
} as const;

export type GameConfig = typeof GameConfig;
